sudo: false
language: node_js
node_js:
- 12
cache: npm

# Only create a new version of build on pushes to hexo branches.
branches:
  only:
  - hexo

# Scripts
script:
- hexo -version
- hexo clean
- hexo generate

deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  github_token: $GH_TOKEN
  target_branch: master
  local-dir: public
  on:
    branch: hexo

# after_success:
# - mkdir .deploy                   # Create a folder to use for teh pages branch
# - cd .deploy
# - git clone --depth 1 --branch gh-pages --single-branch $DEPLOY_REPO . || (git init && git remote add -t gh-pages origin $DEPLOY_REPO)
# - rm -rf ./*                      # Clear old verion
# - cp -r ../public/* .             # Copy over files for new version
# - git add -A .          
# - git commit -m 'Site updated'    # Make a new commit for new version
# - git branch -m gh-pages
# - git push -q -u origin gh-pages  # Push silently so we don't leak information